// Create this file: frontend/src/stockTickers.js

// Export function to load stock tickers
export const loadStockTickers = async () => {
    try {
        const response = await fetch('/stockTickers.json');
        const data = await response.json();
        return data;
    } catch (error) {
        console.error('Failed to load stock tickers:', error);
        return DEFAULT_TICKERS;
    }
};

// Sample of stock tickers - for the full 5,497 list, you'll need to:
// 1. Create a file called stockTickers.json in your frontend/public folder
// 2. Get the full list from a financial API or dataset
// 3. Format it as shown below

export const DEFAULT_TICKERS = [
    { symbol: 'A', name: 'Agilent Technologies Inc.' },
    { symbol: 'AA', name: 'Alcoa Corporation' },
    { symbol: 'AAL', name: 'American Airlines Group Inc.' },
    { symbol: 'AAPL', name: 'Apple Inc.' },
    { symbol: 'ABBV', name: 'AbbVie Inc.' },
    { symbol: 'ABC', name: 'AmerisourceBergen Corporation' },
    { symbol: 'ABMD', name: 'Abiomed Inc.' },
    { symbol: 'ABNB', name: 'Airbnb Inc.' },
    { symbol: 'ABT', name: 'Abbott Laboratories' },
    { symbol: 'ACGL', name: 'Arch Capital Group Ltd.' },
    { symbol: 'ACN', name: 'Accenture plc' },
    { symbol: 'ADBE', name: 'Adobe Inc.' },
    { symbol: 'ADI', name: 'Analog Devices Inc.' },
    { symbol: 'ADM', name: 'Archer-Daniels-Midland Company' },
    { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
    { symbol: 'ADSK', name: 'Autodesk Inc.' },
    { symbol: 'AEE', name: 'Ameren Corporation' },
    { symbol: 'AEP', name: 'American Electric Power Company Inc.' },
    { symbol: 'AES', name: 'The AES Corporation' },
    { symbol: 'AFL', name: 'Aflac Incorporated' },
    { symbol: 'AIG', name: 'American International Group Inc.' },
    { symbol: 'AIZ', name: 'Assurant Inc.' },
    { symbol: 'AJG', name: 'Arthur J. Gallagher & Co.' },
    { symbol: 'AKAM', name: 'Akamai Technologies Inc.' },
    { symbol: 'ALB', name: 'Albemarle Corporation' },
    { symbol: 'ALGN', name: 'Align Technology Inc.' },
    { symbol: 'ALK', name: 'Alaska Air Group Inc.' },
    { symbol: 'ALL', name: 'The Allstate Corporation' },
    { symbol: 'ALLE', name: 'Allegion plc' },
    { symbol: 'AMAT', name: 'Applied Materials Inc.' },
    { symbol: 'AMCR', name: 'Amcor plc' },
    { symbol: 'AMD', name: 'Advanced Micro Devices Inc.' },
    { symbol: 'AME', name: 'AMETEK Inc.' },
    { symbol: 'AMGN', name: 'Amgen Inc.' },
    { symbol: 'AMP', name: 'Ameriprise Financial Inc.' },
    { symbol: 'AMT', name: 'American Tower Corporation' },
    { symbol: 'AMZN', name: 'Amazon.com Inc.' },
    { symbol: 'ANET', name: 'Arista Networks Inc.' },
    { symbol: 'ANSS', name: 'ANSYS Inc.' },
    { symbol: 'ANTM', name: 'Anthem Inc.' },
    { symbol: 'AON', name: 'Aon plc' },
    { symbol: 'AOS', name: 'A. O. Smith Corporation' },
    { symbol: 'APA', name: 'APA Corporation' },
    { symbol: 'APD', name: 'Air Products and Chemicals Inc.' },
    { symbol: 'APH', name: 'Amphenol Corporation' },
    { symbol: 'APTV', name: 'Aptiv PLC' },
    { symbol: 'ARE', name: 'Alexandria Real Estate Equities Inc.' },
    { symbol: 'ATO', name: 'Atmos Energy Corporation' },
    { symbol: 'ATVI', name: 'Activision Blizzard Inc.' },
    { symbol: 'AVB', name: 'AvalonBay Communities Inc.' },
    { symbol: 'AVGO', name: 'Broadcom Inc.' },
    { symbol: 'AVY', name: 'Avery Dennison Corporation' },
    { symbol: 'AWK', name: 'American Water Works Company Inc.' },
    { symbol: 'AXP', name: 'American Express Company' },
    { symbol: 'AZO', name: 'AutoZone Inc.' },
    { symbol: 'BA', name: 'The Boeing Company' },
    { symbol: 'BAC', name: 'Bank of America Corporation' },
    { symbol: 'BAX', name: 'Baxter International Inc.' },
    { symbol: 'BBWI', name: 'Bath & Body Works Inc.' },
    { symbol: 'BBY', name: 'Best Buy Co. Inc.' },
    { symbol: 'BDX', name: 'Becton, Dickinson and Company' },
    { symbol: 'BEN', name: 'Franklin Resources Inc.' },
    { symbol: 'BIIB', name: 'Biogen Inc.' },
    { symbol: 'BIO', name: 'Bio-Rad Laboratories Inc.' },
    { symbol: 'BK', name: 'The Bank of New York Mellon Corporation' },
    { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
    { symbol: 'BKR', name: 'Baker Hughes Company' },
    { symbol: 'BLK', name: 'BlackRock Inc.' },
    { symbol: 'BLL', name: 'Ball Corporation' },
    { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
    { symbol: 'BR', name: 'Broadridge Financial Solutions Inc.' },
    { symbol: 'BRK.A', name: 'Berkshire Hathaway Inc. Class A' },
    { symbol: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B' },
    { symbol: 'BRO', name: 'Brown & Brown Inc.' },
    { symbol: 'BSX', name: 'Boston Scientific Corporation' },
    { symbol: 'BWA', name: 'BorgWarner Inc.' },
    { symbol: 'BXP', name: 'Boston Properties Inc.' },
    { symbol: 'C', name: 'Citigroup Inc.' },
    { symbol: 'CAG', name: 'Conagra Brands Inc.' },
    { symbol: 'CAH', name: 'Cardinal Health Inc.' },
    { symbol: 'CARR', name: 'Carrier Global Corporation' },
    { symbol: 'CAT', name: 'Caterpillar Inc.' },
    { symbol: 'CB', name: 'Chubb Limited' },
    { symbol: 'CBOE', name: 'Cboe Global Markets Inc.' },
    { symbol: 'CBRE', name: 'CBRE Group Inc.' },
    { symbol: 'CCI', name: 'Crown Castle International Corp.' },
    { symbol: 'CCL', name: 'Carnival Corporation' },
    { symbol: 'CDNS', name: 'Cadence Design Systems Inc.' },
    { symbol: 'CDW', name: 'CDW Corporation' },
    { symbol: 'CE', name: 'Celanese Corporation' },
    { symbol: 'CEG', name: 'Constellation Energy Corporation' },
    { symbol: 'CERN', name: 'Cerner Corporation' },
    { symbol: 'CF', name: 'CF Industries Holdings Inc.' },
    { symbol: 'CFG', name: 'Citizens Financial Group Inc.' },
    { symbol: 'CHD', name: 'Church & Dwight Co. Inc.' },
    { symbol: 'CHRW', name: 'C.H. Robinson Worldwide Inc.' },
    { symbol: 'CHTR', name: 'Charter Communications Inc.' },
    { symbol: 'CI', name: 'Cigna Corporation' },
    { symbol: 'CINF', name: 'Cincinnati Financial Corporation' },
    { symbol: 'CL', name: 'Colgate-Palmolive Company' },
    { symbol: 'CLX', name: 'The Clorox Company' },
    { symbol: 'CMA', name: 'Comerica Incorporated' },
    { symbol: 'CMCSA', name: 'Comcast Corporation' },
    { symbol: 'CME', name: 'CME Group Inc.' },
    { symbol: 'CMG', name: 'Chipotle Mexican Grill Inc.' },
    { symbol: 'CMI', name: 'Cummins Inc.' },
    { symbol: 'CMS', name: 'CMS Energy Corporation' },
    { symbol: 'CNC', name: 'Centene Corporation' },
    { symbol: 'CNP', name: 'CenterPoint Energy Inc.' },
    { symbol: 'COF', name: 'Capital One Financial Corporation' },
    { symbol: 'COO', name: 'The Cooper Companies Inc.' },
    { symbol: 'COP', name: 'ConocoPhillips' },
    { symbol: 'COST', name: 'Costco Wholesale Corporation' },
    { symbol: 'CPB', name: 'Campbell Soup Company' },
    { symbol: 'CPRT', name: 'Copart Inc.' },
    { symbol: 'CRL', name: 'Charles River Laboratories International Inc.' },
    { symbol: 'CRM', name: 'Salesforce Inc.' },
    { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
    { symbol: 'CSX', name: 'CSX Corporation' },
    { symbol: 'CTAS', name: 'Cintas Corporation' },
    { symbol: 'CTLT', name: 'Catalent Inc.' },
    { symbol: 'CTRA', name: 'Coterra Energy Inc.' },
    { symbol: 'CTSH', name: 'Cognizant Technology Solutions Corporation' },
    { symbol: 'CTVA', name: 'Corteva Inc.' },
    { symbol: 'CTXS', name: 'Citrix Systems Inc.' },
    { symbol: 'CVS', name: 'CVS Health Corporation' },
    { symbol: 'CVX', name: 'Chevron Corporation' },
    { symbol: 'CZR', name: 'Caesars Entertainment Inc.' },
    { symbol: 'D', name: 'Dominion Energy Inc.' },
    { symbol: 'DAL', name: 'Delta Air Lines Inc.' },
    { symbol: 'DD', name: 'DuPont de Nemours Inc.' },
    { symbol: 'DE', name: 'Deere & Company' },
    { symbol: 'DFS', name: 'Discover Financial Services' },
    { symbol: 'DG', name: 'Dollar General Corporation' },
    { symbol: 'DGX', name: 'Quest Diagnostics Incorporated' },
    { symbol: 'DHI', name: 'D.R. Horton Inc.' },
    { symbol: 'DHR', name: 'Danaher Corporation' },
    { symbol: 'DIS', name: 'The Walt Disney Company' },
    { symbol: 'DISH', name: 'DISH Network Corporation' },
    { symbol: 'DLR', name: 'Digital Realty Trust Inc.' },
    { symbol: 'DLTR', name: 'Dollar Tree Inc.' },
    { symbol: 'DOV', name: 'Dover Corporation' },
    { symbol: 'DOW', name: 'Dow Inc.' },
    { symbol: 'DPZ', name: 'Domino\'s Pizza Inc.' },
    { symbol: 'DRE', name: 'Duke Realty Corporation' },
    { symbol: 'DRI', name: 'Darden Restaurants Inc.' },
    { symbol: 'DTE', name: 'DTE Energy Company' },
    { symbol: 'DUK', name: 'Duke Energy Corporation' },
    { symbol: 'DVA', name: 'DaVita Inc.' },
    { symbol: 'DVN', name: 'Devon Energy Corporation' },
    { symbol: 'DXC', name: 'DXC Technology Company' },
    { symbol: 'DXCM', name: 'DexCom Inc.' },
    { symbol: 'EA', name: 'Electronic Arts Inc.' },
    { symbol: 'EBAY', name: 'eBay Inc.' },
    { symbol: 'ECL', name: 'Ecolab Inc.' },
    { symbol: 'ED', name: 'Consolidated Edison Inc.' },
    { symbol: 'EFX', name: 'Equifax Inc.' },
    { symbol: 'EIX', name: 'Edison International' },
    { symbol: 'EL', name: 'The Estée Lauder Companies Inc.' },
    { symbol: 'EMN', name: 'Eastman Chemical Company' },
    { symbol: 'EMR', name: 'Emerson Electric Co.' },
    { symbol: 'ENPH', name: 'Enphase Energy Inc.' },
    { symbol: 'EOG', name: 'EOG Resources Inc.' },
    { symbol: 'EQIX', name: 'Equinix Inc.' },
    { symbol: 'EQR', name: 'Equity Residential' },
    { symbol: 'ES', name: 'Eversource Energy' },
    { symbol: 'ESS', name: 'Essex Property Trust Inc.' },
    { symbol: 'ETN', name: 'Eaton Corporation plc' },
    { symbol: 'ETR', name: 'Entergy Corporation' },
    { symbol: 'ETSY', name: 'Etsy Inc.' },
    { symbol: 'EVRG', name: 'Evergy Inc.' },
    { symbol: 'EW', name: 'Edwards Lifesciences Corporation' },
    { symbol: 'EXC', name: 'Exelon Corporation' },
    { symbol: 'EXPD', name: 'Expeditors International of Washington Inc.' },
    { symbol: 'EXPE', name: 'Expedia Group Inc.' },
    { symbol: 'EXR', name: 'Extra Space Storage Inc.' },
    { symbol: 'F', name: 'Ford Motor Company' },
    { symbol: 'FANG', name: 'Diamondback Energy Inc.' },
    { symbol: 'FAST', name: 'Fastenal Company' },
    { symbol: 'FB', name: 'Meta Platforms Inc.' },
    { symbol: 'FBHS', name: 'Fortune Brands Home & Security Inc.' },
    { symbol: 'FCX', name: 'Freeport-McMoRan Inc.' },
    { symbol: 'FDS', name: 'FactSet Research Systems Inc.' },
    { symbol: 'FDX', name: 'FedEx Corporation' },
    { symbol: 'FE', name: 'FirstEnergy Corp.' },
    { symbol: 'FFIV', name: 'F5 Inc.' },
    { symbol: 'FIS', name: 'Fidelity National Information Services Inc.' },
    { symbol: 'FISV', name: 'Fiserv Inc.' },
    { symbol: 'FITB', name: 'Fifth Third Bancorp' },
    { symbol: 'FLT', name: 'FleetCor Technologies Inc.' },
    { symbol: 'FMC', name: 'FMC Corporation' },
    { symbol: 'FOX', name: 'Fox Corporation Class B' },
    { symbol: 'FOXA', name: 'Fox Corporation Class A' },
    { symbol: 'FRC', name: 'First Republic Bank' },
    { symbol: 'FRT', name: 'Federal Realty Investment Trust' },
    { symbol: 'FTNT', name: 'Fortinet Inc.' },
    { symbol: 'FTV', name: 'Fortive Corporation' },
    { symbol: 'GD', name: 'General Dynamics Corporation' },
    { symbol: 'GE', name: 'General Electric Company' },
    { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
    { symbol: 'GIS', name: 'General Mills Inc.' },
    { symbol: 'GL', name: 'Globe Life Inc.' },
    { symbol: 'GLW', name: 'Corning Incorporated' },
    { symbol: 'GM', name: 'General Motors Company' },
    { symbol: 'GNRC', name: 'Generac Holdings Inc.' },
    { symbol: 'GOOG', name: 'Alphabet Inc. Class C' },
    { symbol: 'GOOGL', name: 'Alphabet Inc. Class A' },
    { symbol: 'GPC', name: 'Genuine Parts Company' },
    { symbol: 'GPN', name: 'Global Payments Inc.' },
    { symbol: 'GPS', name: 'The Gap Inc.' },
    { symbol: 'GRMN', name: 'Garmin Ltd.' },
    { symbol: 'GS', name: 'The Goldman Sachs Group Inc.' },
    { symbol: 'GWW', name: 'W.W. Grainger Inc.' },
    { symbol: 'HAL', name: 'Halliburton Company' },
    { symbol: 'HAS', name: 'Hasbro Inc.' },
    { symbol: 'HBAN', name: 'Huntington Bancshares Incorporated' },
    { symbol: 'HCA', name: 'HCA Healthcare Inc.' },
    { symbol: 'HD', name: 'The Home Depot Inc.' },
    { symbol: 'HES', name: 'Hess Corporation' },
    { symbol: 'HIG', name: 'The Hartford Financial Services Group Inc.' },
    { symbol: 'HII', name: 'Huntington Ingalls Industries Inc.' },
    { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc.' },
    { symbol: 'HOLX', name: 'Hologic Inc.' },
    { symbol: 'HON', name: 'Honeywell International Inc.' },
    { symbol: 'HPE', name: 'Hewlett Packard Enterprise Company' },
    { symbol: 'HPQ', name: 'HP Inc.' },
    { symbol: 'HRL', name: 'Hormel Foods Corporation' },
    { symbol: 'HSIC', name: 'Henry Schein Inc.' },
    { symbol: 'HST', name: 'Host Hotels & Resorts Inc.' },
    { symbol: 'HSY', name: 'The Hershey Company' },
    { symbol: 'HUM', name: 'Humana Inc.' },
    { symbol: 'HWM', name: 'Howmet Aerospace Inc.' },
    { symbol: 'IBM', name: 'International Business Machines Corporation' },
    { symbol: 'ICE', name: 'Intercontinental Exchange Inc.' },
    { symbol: 'IDXX', name: 'IDEXX Laboratories Inc.' },
    { symbol: 'IEX', name: 'IDEX Corporation' },
    { symbol: 'IFF', name: 'International Flavors & Fragrances Inc.' },
    { symbol: 'ILMN', name: 'Illumina Inc.' },
    { symbol: 'INCY', name: 'Incyte Corporation' },
    { symbol: 'INTC', name: 'Intel Corporation' },
    { symbol: 'INTU', name: 'Intuit Inc.' },
    { symbol: 'IP', name: 'International Paper Company' },
    { symbol: 'IPG', name: 'The Interpublic Group of Companies Inc.' },
    { symbol: 'IPGP', name: 'IPG Photonics Corporation' },
    { symbol: 'IQV', name: 'IQVIA Holdings Inc.' },
    { symbol: 'IR', name: 'Ingersoll Rand Inc.' },
    { symbol: 'IRM', name: 'Iron Mountain Incorporated' },
    { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
    { symbol: 'IT', name: 'Gartner Inc.' },
    { symbol: 'ITW', name: 'Illinois Tool Works Inc.' },
    { symbol: 'IVZ', name: 'Invesco Ltd.' },
    { symbol: 'J', name: 'Jacobs Engineering Group Inc.' },
    { symbol: 'JBHT', name: 'J.B. Hunt Transport Services Inc.' },
    { symbol: 'JCI', name: 'Johnson Controls International plc' },
    { symbol: 'JKHY', name: 'Jack Henry & Associates Inc.' },
    { symbol: 'JNJ', name: 'Johnson & Johnson' },
    { symbol: 'JNPR', name: 'Juniper Networks Inc.' },
    { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
    { symbol: 'K', name: 'Kellogg Company' },
    { symbol: 'KEY', name: 'KeyCorp' },
    { symbol: 'KEYS', name: 'Keysight Technologies Inc.' },
    { symbol: 'KHC', name: 'The Kraft Heinz Company' },
    { symbol: 'KIM', name: 'Kimco Realty Corporation' },
    { symbol: 'KLAC', name: 'KLA Corporation' },
    { symbol: 'KMB', name: 'Kimberly-Clark Corporation' },
    { symbol: 'KMI', name: 'Kinder Morgan Inc.' },
    { symbol: 'KMX', name: 'CarMax Inc.' },
    { symbol: 'KO', name: 'The Coca-Cola Company' },
    { symbol: 'KR', name: 'The Kroger Co.' },
    { symbol: 'L', name: 'Loews Corporation' },
    { symbol: 'LDOS', name: 'Leidos Holdings Inc.' },
    { symbol: 'LEN', name: 'Lennar Corporation' },
    { symbol: 'LH', name: 'Laboratory Corporation of America Holdings' },
    { symbol: 'LHX', name: 'L3Harris Technologies Inc.' },
    { symbol: 'LIN', name: 'Linde plc' },
    { symbol: 'LKQ', name: 'LKQ Corporation' },
    { symbol: 'LLY', name: 'Eli Lilly and Company' },
    { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
    { symbol: 'LNC', name: 'Lincoln National Corporation' },
    { symbol: 'LNT', name: 'Alliant Energy Corporation' },
    { symbol: 'LOW', name: 'Lowe\'s Companies Inc.' },
    { symbol: 'LRCX', name: 'Lam Research Corporation' },
    { symbol: 'LUMN', name: 'Lumen Technologies Inc.' },
    { symbol: 'LUV', name: 'Southwest Airlines Co.' },
    { symbol: 'LVS', name: 'Las Vegas Sands Corp.' },
    { symbol: 'LW', name: 'Lamb Weston Holdings Inc.' },
    { symbol: 'LYB', name: 'LyondellBasell Industries N.V.' },
    { symbol: 'LYV', name: 'Live Nation Entertainment Inc.' },
    { symbol: 'MA', name: 'Mastercard Incorporated' },
    { symbol: 'MAA', name: 'Mid-America Apartment Communities Inc.' },
    { symbol: 'MAR', name: 'Marriott International Inc.' },
    { symbol: 'MAS', name: 'Masco Corporation' },
    { symbol: 'MCD', name: 'McDonald\'s Corporation' },
    { symbol: 'MCHP', name: 'Microchip Technology Incorporated' },
    { symbol: 'MCK', name: 'McKesson Corporation' },
    { symbol: 'MCO', name: 'Moody\'s Corporation' },
    { symbol: 'MDLZ', name: 'Mondelez International Inc.' },
    { symbol: 'MDT', name: 'Medtronic plc' },
    { symbol: 'MET', name: 'MetLife Inc.' },
    { symbol: 'META', name: 'Meta Platforms Inc.' },
    { symbol: 'MGM', name: 'MGM Resorts International' },
    { symbol: 'MHK', name: 'Mohawk Industries Inc.' },
    { symbol: 'MKC', name: 'McCormick & Company Incorporated' },
    { symbol: 'MKTX', name: 'MarketAxess Holdings Inc.' },
    { symbol: 'MLM', name: 'Martin Marietta Materials Inc.' },
    { symbol: 'MMC', name: 'Marsh & McLennan Companies Inc.' },
    { symbol: 'MMM', name: '3M Company' },
    { symbol: 'MNST', name: 'Monster Beverage Corporation' },
    { symbol: 'MO', name: 'Altria Group Inc.' },
    { symbol: 'MOH', name: 'Molina Healthcare Inc.' },
    { symbol: 'MOS', name: 'The Mosaic Company' },
    { symbol: 'MPC', name: 'Marathon Petroleum Corporation' },
    { symbol: 'MPWR', name: 'Monolithic Power Systems Inc.' },
    { symbol: 'MRK', name: 'Merck & Co. Inc.' },
    { symbol: 'MRNA', name: 'Moderna Inc.' },
    { symbol: 'MRO', name: 'Marathon Oil Corporation' },
    { symbol: 'MS', name: 'Morgan Stanley' },
    { symbol: 'MSCI', name: 'MSCI Inc.' },
    { symbol: 'MSFT', name: 'Microsoft Corporation' },
    { symbol: 'MSI', name: 'Motorola Solutions Inc.' },
    { symbol: 'MTB', name: 'M&T Bank Corporation' },
    { symbol: 'MTCH', name: 'Match Group Inc.' },
    { symbol: 'MTD', name: 'Mettler-Toledo International Inc.' },
    { symbol: 'MU', name: 'Micron Technology Inc.' },
    { symbol: 'NCLH', name: 'Norwegian Cruise Line Holdings Ltd.' },
    { symbol: 'NDAQ', name: 'Nasdaq Inc.' },
    { symbol: 'NDSN', name: 'Nordson Corporation' },
    { symbol: 'NEE', name: 'NextEra Energy Inc.' },
    { symbol: 'NEM', name: 'Newmont Corporation' },
    { symbol: 'NFLX', name: 'Netflix Inc.' },
    { symbol: 'NI', name: 'NiSource Inc.' },
    { symbol: 'NKE', name: 'NIKE Inc.' },
    { symbol: 'NLOK', name: 'NortonLifeLock Inc.' },
    { symbol: 'NLSN', name: 'Nielsen Holdings plc' },
    { symbol: 'NOC', name: 'Northrop Grumman Corporation' },
    { symbol: 'NOW', name: 'ServiceNow Inc.' },
    { symbol: 'NRG', name: 'NRG Energy Inc.' },
    { symbol: 'NSC', name: 'Norfolk Southern Corporation' },
    { symbol: 'NTAP', name: 'NetApp Inc.' },
    { symbol: 'NTRS', name: 'Northern Trust Corporation' },
    { symbol: 'NUE', name: 'Nucor Corporation' },
    { symbol: 'NVDA', name: 'NVIDIA Corporation' },
    { symbol: 'NVR', name: 'NVR Inc.' },
    { symbol: 'NWL', name: 'Newell Brands Inc.' },
    { symbol: 'NWS', name: 'News Corporation Class B' },
    { symbol: 'NWSA', name: 'News Corporation Class A' },
    { symbol: 'NXPI', name: 'NXP Semiconductors N.V.' },
    { symbol: 'O', name: 'Realty Income Corporation' },
    { symbol: 'ODFL', name: 'Old Dominion Freight Line Inc.' },
    { symbol: 'OGN', name: 'Organon & Co.' },
    { symbol: 'OKE', name: 'ONEOK Inc.' },
    { symbol: 'OMC', name: 'Omnicom Group Inc.' },
    { symbol: 'ORCL', name: 'Oracle Corporation' },
    { symbol: 'ORLY', name: 'O\'Reilly Automotive Inc.' },
    { symbol: 'OTIS', name: 'Otis Worldwide Corporation' },
    { symbol: 'OXY', name: 'Occidental Petroleum Corporation' },
    { symbol: 'PARA', name: 'Paramount Global' },
    { symbol: 'PAYC', name: 'Paycom Software Inc.' },
    { symbol: 'PAYX', name: 'Paychex Inc.' },
    { symbol: 'PBCT', name: 'People\'s United Financial Inc.' },
    { symbol: 'PCAR', name: 'PACCAR Inc.' },
    { symbol: 'PEAK', name: 'Healthpeak Properties Inc.' },
    { symbol: 'PEG', name: 'Public Service Enterprise Group Incorporated' },
    { symbol: 'PENN', name: 'Penn National Gaming Inc.' },
    { symbol: 'PEP', name: 'PepsiCo Inc.' },
    { symbol: 'PFE', name: 'Pfizer Inc.' },
    { symbol: 'PFG', name: 'Principal Financial Group Inc.' },
    { symbol: 'PG', name: 'The Procter & Gamble Company' },
    { symbol: 'PGR', name: 'The Progressive Corporation' },
    { symbol: 'PH', name: 'Parker-Hannifin Corporation' },
    { symbol: 'PHM', name: 'PulteGroup Inc.' },
    { symbol: 'PKG', name: 'Packaging Corporation of America' },
    { symbol: 'PKI', name: 'PerkinElmer Inc.' },
    { symbol: 'PLD', name: 'Prologis Inc.' },
    { symbol: 'PM', name: 'Philip Morris International Inc.' },
    { symbol: 'PNC', name: 'The PNC Financial Services Group Inc.' },
    { symbol: 'PNR', name: 'Pentair plc' },
    { symbol: 'PNW', name: 'Pinnacle West Capital Corporation' },
    { symbol: 'POOL', name: 'Pool Corporation' },
    { symbol: 'PPG', name: 'PPG Industries Inc.' },
    { symbol: 'PPL', name: 'PPL Corporation' },
    { symbol: 'PRU', name: 'Prudential Financial Inc.' },
    { symbol: 'PSA', name: 'Public Storage' },
    { symbol: 'PSX', name: 'Phillips 66' },
    { symbol: 'PTC', name: 'PTC Inc.' },
    { symbol: 'PVH', name: 'PVH Corp.' },
    { symbol: 'PWR', name: 'Quanta Services Inc.' },
    { symbol: 'PXD', name: 'Pioneer Natural Resources Company' },
    { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
    { symbol: 'QCOM', name: 'QUALCOMM Incorporated' },
    { symbol: 'QRVO', name: 'Qorvo Inc.' },
    { symbol: 'RCL', name: 'Royal Caribbean Cruises Ltd.' },
    { symbol: 'RE', name: 'Everest Re Group Ltd.' },
    { symbol: 'REG', name: 'Regency Centers Corporation' },
    { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
    { symbol: 'RF', name: 'Regions Financial Corporation' },
    { symbol: 'RHI', name: 'Robert Half International Inc.' },
    { symbol: 'RJF', name: 'Raymond James Financial Inc.' },
    { symbol: 'RL', name: 'Ralph Lauren Corporation' },
    { symbol: 'RMD', name: 'ResMed Inc.' },
    { symbol: 'ROK', name: 'Rockwell Automation Inc.' },
    { symbol: 'ROL', name: 'Rollins Inc.' },
    { symbol: 'ROP', name: 'Roper Technologies Inc.' },
    { symbol: 'ROST', name: 'Ross Stores Inc.' },
    { symbol: 'RSG', name: 'Republic Services Inc.' },
    { symbol: 'RTX', name: 'Raytheon Technologies Corporation' },
    { symbol: 'SBAC', name: 'SBA Communications Corporation' },
    { symbol: 'SBNY', name: 'Signature Bank' },
    { symbol: 'SBUX', name: 'Starbucks Corporation' },
    { symbol: 'SCHW', name: 'The Charles Schwab Corporation' },
    { symbol: 'SEDG', name: 'SolarEdge Technologies Inc.' },
    { symbol: 'SEE', name: 'Sealed Air Corporation' },
    { symbol: 'SHW', name: 'The Sherwin-Williams Company' },
    { symbol: 'SIVB', name: 'SVB Financial Group' },
    { symbol: 'SJM', name: 'The J. M. Smucker Company' },
    { symbol: 'SLB', name: 'Schlumberger Limited' },
    { symbol: 'SNA', name: 'Snap-on Incorporated' },
    { symbol: 'SNPS', name: 'Synopsys Inc.' },
    { symbol: 'SO', name: 'The Southern Company' },
    { symbol: 'SPG', name: 'Simon Property Group Inc.' },
    { symbol: 'SPGI', name: 'S&P Global Inc.' },
    { symbol: 'SRE', name: 'Sempra Energy' },
    { symbol: 'STE', name: 'STERIS plc' },
    { symbol: 'STT', name: 'State Street Corporation' },
    { symbol: 'STX', name: 'Seagate Technology Holdings plc' },
    { symbol: 'STZ', name: 'Constellation Brands Inc.' },
    { symbol: 'SWK', name: 'Stanley Black & Decker Inc.' },
    { symbol: 'SWKS', name: 'Skyworks Solutions Inc.' },
    { symbol: 'SYF', name: 'Synchrony Financial' },
    { symbol: 'SYK', name: 'Stryker Corporation' },
    { symbol: 'SYY', name: 'Sysco Corporation' },
    { symbol: 'T', name: 'AT&T Inc.' },
    { symbol: 'TAP', name: 'Molson Coors Beverage Company' },
    { symbol: 'TDG', name: 'TransDigm Group Incorporated' },
    { symbol: 'TDY', name: 'Teledyne Technologies Incorporated' },
    { symbol: 'TECH', name: 'Bio-Techne Corporation' },
    { symbol: 'TEL', name: 'TE Connectivity Ltd.' },
    { symbol: 'TER', name: 'Teradyne Inc.' },
    { symbol: 'TFC', name: 'Truist Financial Corporation' },
    { symbol: 'TFX', name: 'Teleflex Incorporated' },
    { symbol: 'TGT', name: 'Target Corporation' },
    { symbol: 'TJX', name: 'The TJX Companies Inc.' },
    { symbol: 'TMO', name: 'Thermo Fisher Scientific Inc.' },
    { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
    { symbol: 'TPR', name: 'Tapestry Inc.' },
    { symbol: 'TRMB', name: 'Trimble Inc.' },
    { symbol: 'TROW', name: 'T. Rowe Price Group Inc.' },
    { symbol: 'TRV', name: 'The Travelers Companies Inc.' },
    { symbol: 'TSCO', name: 'Tractor Supply Company' },
    { symbol: 'TSLA', name: 'Tesla Inc.' },
    { symbol: 'TSN', name: 'Tyson Foods Inc.' },
    { symbol: 'TT', name: 'Trane Technologies plc' },
    { symbol: 'TTWO', name: 'Take-Two Interactive Software Inc.' },
    { symbol: 'TXN', name: 'Texas Instruments Incorporated' },
    { symbol: 'TXT', name: 'Textron Inc.' },
    { symbol: 'TYL', name: 'Tyler Technologies Inc.' },
    { symbol: 'UAL', name: 'United Airlines Holdings Inc.' },
    { symbol: 'UDR', name: 'UDR Inc.' },
    { symbol: 'UHS', name: 'Universal Health Services Inc.' },
    { symbol: 'ULTA', name: 'Ulta Beauty Inc.' },
    { symbol: 'UNH', name: 'UnitedHealth Group Incorporated' },
    { symbol: 'UNP', name: 'Union Pacific Corporation' },
    { symbol: 'UPS', name: 'United Parcel Service Inc.' },
    { symbol: 'URI', name: 'United Rentals Inc.' },
    { symbol: 'USB', name: 'U.S. Bancorp' },
    { symbol: 'V', name: 'Visa Inc.' },
    { symbol: 'VFC', name: 'V.F. Corporation' },
    { symbol: 'VIAC', name: 'ViacomCBS Inc.' },
    { symbol: 'VLO', name: 'Valero Energy Corporation' },
    { symbol: 'VMC', name: 'Vulcan Materials Company' },
    { symbol: 'VNO', name: 'Vornado Realty Trust' },
    { symbol: 'VRSK', name: 'Verisk Analytics Inc.' },
    { symbol: 'VRSN', name: 'VeriSign Inc.' },
    { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated' },
    { symbol: 'VTR', name: 'Ventas Inc.' },
    { symbol: 'VTRS', name: 'Viatris Inc.' },
    { symbol: 'VZ', name: 'Verizon Communications Inc.' },
    { symbol: 'WAB', name: 'Westinghouse Air Brake Technologies Corporation' },
    { symbol: 'WAT', name: 'Waters Corporation' },
    { symbol: 'WBA', name: 'Walgreens Boots Alliance Inc.' },
    { symbol: 'WBD', name: 'Warner Bros. Discovery Inc.' },
    { symbol: 'WDC', name: 'Western Digital Corporation' },
    { symbol: 'WEC', name: 'WEC Energy Group Inc.' },
    { symbol: 'WELL', name: 'Welltower Inc.' },
    { symbol: 'WFC', name: 'Wells Fargo & Company' },
    { symbol: 'WHR', name: 'Whirlpool Corporation' },
    { symbol: 'WM', name: 'Waste Management Inc.' },
    { symbol: 'WMB', name: 'The Williams Companies Inc.' },
    { symbol: 'WMT', name: 'Walmart Inc.' },
    { symbol: 'WRB', name: 'W. R. Berkley Corporation' },
    { symbol: 'WRK', name: 'WestRock Company' },
    { symbol: 'WST', name: 'West Pharmaceutical Services Inc.' },
    { symbol: 'WTW', name: 'Willis Towers Watson Public Limited Company' },
    { symbol: 'WY', name: 'Weyerhaeuser Company' },
    { symbol: 'WYNN', name: 'Wynn Resorts Limited' },
    { symbol: 'XEL', name: 'Xcel Energy Inc.' },
    { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
    { symbol: 'XRAY', name: 'Dentsply Sirona Inc.' },
    { symbol: 'XYL', name: 'Xylem Inc.' },
    { symbol: 'YUM', name: 'Yum! Brands Inc.' },
    { symbol: 'ZBH', name: 'Zimmer Biomet Holdings Inc.' },
    { symbol: 'ZBRA', name: 'Zebra Technologies Corporation' },
    { symbol: 'ZION', name: 'Zions Bancorporation N.A.' },
    { symbol: 'ZTS', name: 'Zoetis Inc.' }
];

// Updated App.js integration
// In your App.js, replace the STOCK_TICKERS constant at the top with:
// import { DEFAULT_TICKERS, loadStockTickers } from './stockTickers';

// Then update your App component to load tickers:
/*
function App() {
  const [stockSymbol, setStockSymbol] = useState('');
  const [timeRange, setTimeRange] = useState('6 Months');
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState(null);
  const [error, setError] = useState(null);
  const [allTickers, setAllTickers] = useState(DEFAULT_TICKERS);

  // Load stock tickers on component mount
  useEffect(() => {
    loadStockTickers().then(tickers => {
      setAllTickers(tickers);
    });
  }, []);

  // Then pass allTickers to StockSidebar:
  // <StockSidebar onSelectStock={handleStockSelect} selectedStock={stockSymbol} tickers={allTickers} />
}
*/

// For the full 5,497 tickers, create a file: frontend/public/stockTickers.json
// with this format:
/*
[
  {"symbol": "A", "name": "Agilent Technologies Inc."},
  {"symbol": "AA", "name": "Alcoa Corporation"},
  ... all 5,497 tickers ...
]
*/

// You can get the full list from:
// 1. Yahoo Finance API
// 2. Alpha Vantage API
// 3. IEX Cloud
// 4. Financial data providers
// 5. SEC EDGAR database